// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Superheroes.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class BiographyModel
    {
        /// <summary>
        /// Initializes a new instance of the BiographyModel class.
        /// </summary>
        public BiographyModel() { }

        /// <summary>
        /// Initializes a new instance of the BiographyModel class.
        /// </summary>
        public BiographyModel(string fullName = default(string), string alterEgos = default(string), IList<string> aliases = default(IList<string>), string placeOfBirth = default(string), string firstAppearance = default(string), string publisher = default(string), string alignment = default(string))
        {
            FullName = fullName;
            AlterEgos = alterEgos;
            Aliases = aliases;
            PlaceOfBirth = placeOfBirth;
            FirstAppearance = firstAppearance;
            Publisher = publisher;
            Alignment = alignment;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fullName")]
        public string FullName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alterEgos")]
        public string AlterEgos { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aliases")]
        public IList<string> Aliases { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "placeOfBirth")]
        public string PlaceOfBirth { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "firstAppearance")]
        public string FirstAppearance { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "publisher")]
        public string Publisher { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "alignment")]
        public string Alignment { get; set; }

    }
}
