// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Superheroes.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ConnectionsModel
    {
        /// <summary>
        /// Initializes a new instance of the ConnectionsModel class.
        /// </summary>
        public ConnectionsModel() { }

        /// <summary>
        /// Initializes a new instance of the ConnectionsModel class.
        /// </summary>
        public ConnectionsModel(string groupAffiliation = default(string), string relatives = default(string))
        {
            GroupAffiliation = groupAffiliation;
            Relatives = relatives;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "groupAffiliation")]
        public string GroupAffiliation { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "relatives")]
        public string Relatives { get; set; }

    }
}
