// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Superheroes.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class ImagesModel
    {
        /// <summary>
        /// Initializes a new instance of the ImagesModel class.
        /// </summary>
        public ImagesModel() { }

        /// <summary>
        /// Initializes a new instance of the ImagesModel class.
        /// </summary>
        public ImagesModel(string xs = default(string), string sm = default(string), string md = default(string), string lg = default(string))
        {
            Xs = xs;
            Sm = sm;
            Md = md;
            Lg = lg;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "xs")]
        public string Xs { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sm")]
        public string Sm { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "md")]
        public string Md { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lg")]
        public string Lg { get; set; }

    }
}
