// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Superheroes.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class AppearanceModel
    {
        /// <summary>
        /// Initializes a new instance of the AppearanceModel class.
        /// </summary>
        public AppearanceModel() { }

        /// <summary>
        /// Initializes a new instance of the AppearanceModel class.
        /// </summary>
        public AppearanceModel(string gender = default(string), string race = default(string), IList<string> height = default(IList<string>), IList<string> weight = default(IList<string>), string eyeColor = default(string), string hairColor = default(string))
        {
            Gender = gender;
            Race = race;
            Height = height;
            Weight = weight;
            EyeColor = eyeColor;
            HairColor = hairColor;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "gender")]
        public string Gender { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "race")]
        public string Race { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public IList<string> Height { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public IList<string> Weight { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eyeColor")]
        public string EyeColor { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "hairColor")]
        public string HairColor { get; set; }

    }
}
