// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Superheroes.Client.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PowerstatsModel
    {
        /// <summary>
        /// Initializes a new instance of the PowerstatsModel class.
        /// </summary>
        public PowerstatsModel() { }

        /// <summary>
        /// Initializes a new instance of the PowerstatsModel class.
        /// </summary>
        public PowerstatsModel(int intelligence, int strength, int speed, int durability, int power, int combat)
        {
            Intelligence = intelligence;
            Strength = strength;
            Speed = speed;
            Durability = durability;
            Power = power;
            Combat = combat;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "intelligence")]
        public int Intelligence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "strength")]
        public int Strength { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "speed")]
        public int Speed { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "durability")]
        public int Durability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "power")]
        public int Power { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "combat")]
        public int Combat { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
